# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-11-12 15:50
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Pin',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('valor', models.CharField(max_length=4, null=True, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Telefono',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero', models.CharField(max_length=11, null=True, unique=True)),
                ('valido', models.NullBooleanField()),
                ('saldo', models.DecimalField(decimal_places=2, default=0, max_digits=6)),
            ],
        ),
        migrations.AddField(
            model_name='pin',
            name='Telefono',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='front_end.Telefono'),
        ),
    ]
