# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-11-06 17:06
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('back_end', '0002_auto_20161102_1449'),
    ]

    operations = [
        migrations.RenameField(
            model_name='sector',
            old_name='Lugar',
            new_name='LugarSector',
        ),
        migrations.AlterUniqueTogether(
            name='sector',
            unique_together=set([('codigo', 'LugarSector')]),
        ),
    ]
