# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-11-08 03:10
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('back_end', '0003_auto_20161106_1406'),
    ]

    operations = [
        migrations.AlterField(
            model_name='entrada',
            name='Asiento',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='back_end.Asiento', unique=True),
        ),
        migrations.AlterField(
            model_name='evento',
            name='afiche',
            field=models.ImageField(null=True, upload_to=b''),
        ),
    ]
