# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-11-12 21:12
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('back_end', '0004_auto_20161108_0010'),
    ]

    operations = [
        migrations.AlterField(
            model_name='evento',
            name='afiche',
            field=models.ImageField(null=True, upload_to=b'afiches_eventos'),
        ),
    ]
