# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-11-12 21:20
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('back_end', '0005_auto_20161112_1812'),
    ]

    operations = [
        migrations.CreateModel(
            name='Afiche',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descripcion', models.CharField(max_length=100, null=True)),
                ('archivo', models.ImageField(null=True, upload_to=b'afiches')),
            ],
        ),
        migrations.RemoveField(
            model_name='evento',
            name='afiche',
        ),
        migrations.AddField(
            model_name='evento',
            name='Afiche',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='back_end.Afiche'),
        ),
    ]
