# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-11-12 21:27
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('back_end', '0006_auto_20161112_1820'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='afiche',
            name='descripcion',
        ),
    ]
