# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-11-14 18:40
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('back_end', '0007_remove_afiche_descripcion'),
    ]

    operations = [
        migrations.RenameField(
            model_name='sector',
            old_name='LugarSector',
            new_name='Lugar',
        ),
        migrations.AlterUniqueTogether(
            name='sector',
            unique_together=set([('codigo', 'Lugar')]),
        ),
    ]
